// EDITA AQUÍ: añade { id: "VIDEO_ID", title: "Título con tu formato" } para nuevos covers
// El botón random usa solo el id. El featured usa id + title.
const COVERS = [
  { id: "VzlxSbGMQHw", title: "キュートなカノジョ (Cute na Kanojo) Ft. IA & OИE" },
  { id: "zRgZu9lGNzU", title: "展示中毒 (Displayholic) Ft. Kasane Teto AI" },
  { id: "_6BE4ihX7-c", title: "404：虚像 (404: False Image) Ft. Otomachi Una & Hanakuma Chifuyu" },
  { id: "0je8d0j8q40", title: "シロクロリバーシ Ft. Kagamine Rin & Len (V4X)" },
  { id: "wScsIKm5hXQ", title: "次元通信 (Signaling) Ft. KazehikiV & GekiyakuV" },
  { id: "2Rm3s24TwEg", title: "メモリー (Memory) Ft. Zundamon" },
  { id: "qM6GWXk4iGY", title: "ラグトレイン (Lagtrain) Ft. IA:[R] & vflower" },
  { id: "c7kfXUIVZug", title: "Larping the Rooms (Looping the Rooms remix) Ft. IA:[R]" },
  { id: "8wX178m281Y", title: "Melt ice cream Ft. Otomachi Una & Macne Nana" },
  { id: "yqfu0hiABJ0", title: "アクマバライ (Exorcist) Ft. Ci Flower, Nurse Robot Type T (TTS) & Otomachi Una" },
  { id: "067AjR4HpVM", title: "ボッカデラベリタ (Bocca della Verità) Ft. Adachi Rei" },
  { id: "NkM2x8PjxMc", title: "サーカス・モンスター (Circus Monster) Ft. Yuma" },
  { id: "nwj_trjcDU8", title: "Cutie Mew Mew Magic Ft. Hatsune Miku" },
  { id: "siQFIverx78", title: "ヤラララ (Yararara) Ft. Regita Vi" },
  { id: "4MWCCJL127E", title: "Bad ∞ End ∞ Night Ft. Meika Hime, Meika Mikoto, IA:[R], Kanade, Yuma, KazehikiV, Hatsune Miku, Kasane Teto & NineZero" },
  { id: "E7N1SFvMQYc", title: "わかれみち (Wakaremichi) Ft. IA:[R], Akita Neru, Meika Hime & Meika Mikoto" },
  { id: "9ooy6tQFfmw", title: "のだ (Noda) Ft. Kafu, Otomachi Una & Namine Ritsu" },
  { id: "CB3ZqPVkYbk", title: "どりーむもーど (DREAMMODE) Ft. Hatsune Miku & Kasane Teto" },
  { id: "Q7RYZhOneVs", title: "Execution Clap Ft. Hatsune Miku & KazehikiV" },
  { id: "ZQfz3Em5h70", title: "アンハッピーリフレイン (Unhappy Refrain) Ft. Hatsune Miku" },
  { id: "1aJ3EwBvA2o", title: "Human Ft. Yuma" },
  { id: "trWCqEU8LrI", title: "Special Relief Committee Ft. Kanade, Chifuyu, Yuma, Yi Xi, asa & Una" },
  { id: "6o8HWHnP4Tw", title: "アイ・アイ・ア (AiAiA) Ft. Kasane Teto AI" },
  { id: "YbSFHu6O_0E", title: "ダダダダダル (Dadadadaru) Ft. vflower & IA:[R]" },
  { id: "FpyCzNmF4mI", title: "ド屑 (Dokuzu) Ft. Yuma" },
  { id: "iJog3LTeBiI", title: "いますぐ輪廻 (Retry Now) Ft. IA, IA ROCKS, IA:[R], IA AI" },
  { id: "gV14fvpaagk", title: "the box Ft. Regita Vi" },
  { id: "XtJfFC1Yb5U", title: "Stale Ft. Hanakuma Chifuyu & Yuma" },
  { id: "ocDKLge1C8A", title: "Ghost Rule Ft. IA:[R]" },
  { id: "uc5RrzSaZPc", title: "INFINITE DEATH Ft. Otomachi Una AI" },
  { id: "isr8YTJKXik", title: "Judge Ft. KazehikiV" },
  { id: "umhCN_uNXv4", title: "Mr.シャーデンフロイデ (Mr. Schadenfreude) Ft. IA:[R], Kanade, vflower, Fukase, Meika Hime, Meika Mikoto, fuiro & Wil" },
  { id: "3rptp_sKu7E", title: "Looping the Rooms Ft. IA:[R]" },
  { id: "s87OQSHo8UA", title: "Sell a friend Ft. IA ROCKS" },
  { id: "naOoF4CmgdU", title: "罰して光 (Punish then Save) Ft. IA:[R]" },
  { id: "M2IWeGthV9w", title: "バグ (Bug) Ft. IA:[R]" },
  { id: "35q6aXr6Hcg", title: "バウムクーヘン・エンドロール (Baumkuchen End Credits) Ft. vflower, IA:[R] & IA" },
  { id: "VRYpL0VOwto", title: "化けの花 (BakenoHana) Ft. IA:[R]" },
  { id: "XOS7tiEuPGc", title: "メズマライザー (Mesmerizer) Ft. IA:[R] & Regita Vi" },
  { id: "70bNznWfDUI", title: "Bad Girl Online Ft. IA:[R] & Yuma" },
  { id: "-KYrJfPSzSw", title: "(Un)Natural Selection (English ver.) Ft. IA:[R]" },
  { id: "fBjo1sokRZ0", title: "ベノム (Venom) Ft. IA:[R]" },
  { id: "gwS1mhLgjwc", title: "Whisper Whisper Whisper Ft. IA:[R]" },
  { id: "DkGzs94BzYI", title: "D/N/A Ft. IA:[R] & Otomachi Una" },
  { id: "icciS7aQqC8", title: "オーバーライド (Override) Ft. Yuma & Otomachi Una" },
  { id: "OCpN-6hyBoc", title: "テトリス (Tetoris) Ft. Yuma" },
  { id: "f_w_oyWyJIQ", title: "聖人君子でありたい (Seijinkunshi de Aritai) Ft. Otomachi Una AI" },
  { id: "UwLlZXKOgLc", title: "MIRA Ft. Otomachi Una AI" },
  { id: "C-KG_CpdyWQ", title: "(Un)Natural Selection Ft. Otomachi Una" },
  { id: "5XZwGf2XFZk", title: "Lemonade Ft. NineZero" },
  { id: "9VQeBsykboQ", title: "祈れやデタラメ (Pray or be Desperate) Ft. Bennet Fantasia" }
];
